StayLive/areas/Levels/Models/Level/LevelVM.cs
using StayLive.Resources;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StayLive.areas.Levels.Level.Models
{
    public class LevelVM
    {
        public int Id { get; set; }
        [Required(ErrorMessageResourceType = typeof(Validations), ErrorMessageResourceName = "Required")]
        public string First { get; set; }
        [Required(ErrorMessageResourceType = typeof(Validations), ErrorMessageResourceName = "Required")]
        public string Second { get; set; }
        [Required(ErrorMessageResourceType = typeof(Validations), ErrorMessageResourceName = "Required")]
        public string Third { get; set; }
        public int FirstTime { get; set; }
        public int SecondTime { get; set; }
        public int? ThirdTime { get; set; }
    }
}

StayLive/areas/Levels/Models/LevelInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StayLive.areas.Levels.Models
{
    public class LevelInfo
    {
        public enum LevelOrder
        {
            First = 1,
            Second = 2,
            Third = 3
        }
    }
}

StayLive/areas/Levels/Controllers/LevelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StayLive.Models;
using StayLive.Helpers;
using StayLive.Controllers;
using StayLive.areas.Levels.Level.Models;

namespace StayLive.areas.Levels.Controllers
{
    public class LevelController : BaseController
    {
        #region Action
        [RoleFilter(Role = areas.Users.Models.UserRoles.Admin)]
        public ActionResult Index()
        {
            LevelVM vm = new LevelVM();
            vm = FillLevelDetails();
            if (vm == null)
                return View("~/Views/Shared/NotFound.cshtml");

            return View(vm);
        }

        [HttpPost]
        [RoleFilter(Role = areas.Users.Models.UserRoles.Admin)]
        public ActionResult Index(LevelVM vm)
        {
            int Id = 0;
            var level = new StayLive.Models.Level();
            if (vm.Id >= 0)
            {
                level.Id = vm.Id;
                level.FirstName = vm.First;
                level.FirstHours = vm.FirstTime;
                level.SecondName = vm.Second;
                level.SecondHours = vm.SecondTime;
                level.ThirdName = vm.Third;
                Id = EditLevel(level);
            }

            if (Id == -1)
            {
                this.MsgError(StayLive.Resources.General.SaveLevel, StayLive.Resources.General.SomethingWentWorng);
                return View(vm);
            }
            else
            {
                this.MsgSavedSuccessfuly();
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region GetterMethods
        [HttpGet]
        [RoleFilter(Role = areas.Users.Models.UserRoles.Admin)]
        public ActionResult LevelsTree()
        {
            var levelTree = new List<TreeModel>();

            var level = dbService.Levels.Where(a => a.CompanyId == SessionHelper.CompanyId.Value).FirstOrDefault();

            if (level != null)
            {
                levelTree.Add(new TreeModel() { id = "level1", text = level.FirstName, parent = "#", state = new NodeState() });
                levelTree.AddRange(GetUsersSubTree((byte)StayLive.areas.Levels.Models.LevelInfo.LevelOrder.First, "level1"));
                levelTree.Add(new TreeModel() { id = "level2", text = level.SecondName, parent = "#", state = new NodeState() });
                levelTree.AddRange(GetUsersSubTree((byte)StayLive.areas.Levels.Models.LevelInfo.LevelOrder.Second, "level2"));
                levelTree.Add(new TreeModel() { id = "level3", text = level.ThirdName, parent = "#", state = new NodeState() });
                levelTree.AddRange(GetUsersSubTree((byte)StayLive.areas.Levels.Models.LevelInfo.LevelOrder.Third, "level3"));
            }

            return Json(new { Data = levelTree }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region PrivateMethodes
        private LevelVM FillLevelDetails()
        {
            LevelVM vm = new LevelVM();
            var level = dbService.Levels.Where(a => a.CompanyId == SessionHelper.CompanyId.Value).FirstOrDefault();

            if (level == null)
                return null;

            vm.Id = level.Id;
            vm.First = level.FirstName;
            vm.FirstTime = level.FirstHours;
            vm.Second = level.SecondName;
            vm.SecondTime = level.SecondHours;
            vm.Third = level.ThirdName;
            vm.ThirdTime = null;
            return vm;
        }

        private int EditLevel(StayLive.Models.Level level)
        {
            try
            {
                var lvl = dbService.Levels.Find(level.Id);
                if (lvl != null)
                {
                    lvl.FirstName = level.FirstName;
                    lvl.FirstHours = level.FirstHours;
                    lvl.SecondName = level.SecondName;
                    lvl.SecondHours = level.SecondHours;
                    lvl.ThirdName = level.ThirdName;
                    dbService.SaveChanges();
                    return level.Id;
                }
                return -1;
            }
            catch (Exception ex)
            {
                return -1;
            }
        }

        private List<TreeModel> GetUsersSubTree(byte LevelId,string FatherId)
        {
            var usersTree = new List<TreeModel>();
            var users = dbService.Users.Where(a => a.Level == LevelId && a.CompanyId == SessionHelper.CompanyId).ToList();

            usersTree.AddRange(users.Select(a => new TreeModel()
            {
                id = a.Id.ToString(),
                parent = FatherId,
                state = new NodeState(),
                text = a.Name
            }));

            usersTree = usersTree.OrderBy(a => a.text).ToList();
            return usersTree;
        }
        #endregion
    }
}

StayLive/areas/Levels/Views/Level/Index.cshtml
@model StayLive.areas.Levels.Level.Models.LevelVM
@{
    ViewBag.Title = StayLive.Resources.General.Levels;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row page-titles">
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            @Html.Breadcrumb(new string[] { StayLive.Resources.General.Levels })
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div id="LevelsTree"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card">
                @using (Html.BeginForm("Index", "Level", new { area = "Levels" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="card-body">
                        @Html.HiddenFor(model => model.Id)
                        <div class="row">
                            <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
                                <div class="floating-labels">
                                    <div class="form-group">
                                        @Html.TextBoxFor(model => model.First, new { @class = "form-control", @Id = "txtFirst" })
                                        <span class="bar"></span>
                                        <label for="txtEmailAddress">@StayLive.Resources.Levels.First</label>
                                        @Html.ValidationMessageFor(model => model.First, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
                                <div class="floating-labels">
                                    <div class="form-group">
                                        @Html.TextBoxFor(model => model.FirstTime, new { @class = "form-control number", @Id = "txtFirstHrs" })
                                        <span class="bar"></span>
                                        <label for="txtFirstHrs">@StayLive.Resources.Levels.Hours</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
                                <div class="floating-labels">
                                    <div class="form-group">
                                        @Html.TextBoxFor(model => model.Second, new { @class = "form-control", @Id = "txtSecond" })
                                        <span class="bar"></span>
                                        <label for="txtSecond">@StayLive.Resources.Levels.Second</label>
                                        @Html.ValidationMessageFor(model => model.Second, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
                                <div class="floating-labels">
                                    <div class="form-group">
                                        @Html.TextBoxFor(model => model.SecondTime, new { @class = "form-control number", @Id = "txtSecondHrs" })
                                        <span class="bar"></span>
                                        <label for="txtSecondHrs">@StayLive.Resources.Levels.Hours</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
                                <div class="floating-labels">
                                    <div class="form-group">
                                        @Html.TextBoxFor(model => model.Third, new { @class = "form-control", @Id = "txtThird" })
                                        <span class="bar"></span>
                                        <label for="txtThird">@StayLive.Resources.Levels.Third</label>
                                        @Html.ValidationMessageFor(model => model.Third, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
                                <div class="floating-labels">
                                    <div class="form-group">
                                        @Html.TextBoxFor(model => model.ThirdTime, new { @class = "form-control number", @Id = "txtThirdHrs", @disabled = true })
                                        <span class="bar"></span>
                                        <label for="txtThirdHrs">@StayLive.Resources.Levels.Hours</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                @*<a href="@Url.Action("", "level", new { @area = "Levels" })" class="btn btn-secondary waves-effect waves-light m-r-5 pull-right">@StayLive.Resources.General.Cancel</a>*@
                                <button type="submit" class="btn btn-primary waves-effect waves-light m-r-5 pull-right">@StayLive.Resources.General.Save</button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>


@Scripts.Render("~/bundles/levels-helpers")

@section scripts{
    <script>
        $(document).ready(function () { LevelsHelper.IndexLoad(); })
    </script>
}